"""empty message

Revision ID: 19b0e2bbbe4c
Revises: 5744a6a7dda6
Create Date: 2025-01-27 15:50:59.069716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b0e2bbbe4c'
down_revision = '5744a6a7dda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'favorites', ['fav_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fav_id')

    # ### end Alembic commands ###
