"""empty message

Revision ID: 2204ea5fe50b
Revises: 7019f88a6783
Create Date: 2025-01-27 12:53:28.527993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2204ea5fe50b'
down_revision = '7019f88a6783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_people_id_fkey', type_='foreignkey')
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_people_id_fkey', 'people', ['people_id'], ['id'])

    # ### end Alembic commands ###
