"""empty message

Revision ID: 28f4e4505ad3
Revises: f13382cc817e
Create Date: 2025-01-24 16:00:26.704293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f4e4505ad3'
down_revision = 'f13382cc817e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.drop_constraint('favourites_people_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favourites_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favourites_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('people_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favourites_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favourites_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key('favourites_people_id_fkey', 'people', ['people_id'], ['id'])

    # ### end Alembic commands ###
