"""empty message

Revision ID: 7019f88a6783
Revises: 88de4fd0958d
Create Date: 2025-01-27 12:42:50.336691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7019f88a6783'
down_revision = '88de4fd0958d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planets_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('planets_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favorites_planets_id_fkey', 'planets', ['planets_id'], ['id'])
        batch_op.create_foreign_key('favorites_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
