"""empty message

Revision ID: 951b51c347c7
Revises: 2204ea5fe50b
Create Date: 2025-01-27 13:04:59.497197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951b51c347c7'
down_revision = '2204ea5fe50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.Integer(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('people_id')

    # ### end Alembic commands ###
