"""empty message

Revision ID: b55f14baf94f
Revises: d26573362dac
Create Date: 2025-01-24 15:46:29.342770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55f14baf94f'
down_revision = 'd26573362dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mass', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.String(length=100), nullable=True))

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('terrain', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.String(length=100), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vehicle_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cost_in_credits', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('length', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('crew', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('passengers', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('max_atmosphering_speed', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cargo_capacity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('consumables', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('edited', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('consumables')
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('max_atmosphering_speed')
        batch_op.drop_column('passengers')
        batch_op.drop_column('crew')
        batch_op.drop_column('length')
        batch_op.drop_column('cost_in_credits')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('vehicle_class')
        batch_op.drop_column('model')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('population')
        batch_op.drop_column('gravity')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('diameter')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('edited')
        batch_op.drop_column('created')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
